version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      - PUID
      - PGID
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - /opt/sonarr:/config
      - /media/tv:/tv
    ports:
      - "8989:${SONARR_PORT}"
  nginx:
    build:
      context: ./automation/nginx
    container_name: nginx
    image: nginx:latest
    environment:
      - ALLOWED_HOSTS
      - COUCHPOTATO_HOST
      - COUCHPOTATO_PORT
      - DELUGE_HOST
      - DELUGE_PORT
      - GHOST_PORT
      - HEADPHONES_HOST
      - HEADPHONES_PORT
      - HTTPS_PORT
      - HTTP_PORT
      - SONARR_PORT
      - SONARR_HOST
      - SSL_CERTIFICATE
      - SSL_CERTIFICATE_KEY
      - SYNOLOGY_HOST
      - SYNOLOGY_INTERNAL_HOST
      - SYNOLOGY_PORT
      - WEB_INTERNAL_HOST
    volumes:
      - ./automation/certs:/etc/nginx/certs:ro
    links:
      - sonarr
    ports:
      - "80:${HTTP_PORT}"
      - "443:${HTTPS_PORT}"
