version: "2.1"
services:
  nginx:
    build:
      context: ./automation/nginx
    container_name: nginx
    image: nginx:latest
    environment:
      - ALLOWED_HOSTS
      - COUCHPOTATO_HOST
      - COUCHPOTATO_PORT
      - DELUGE_HOST
      - DELUGE_PORT
      - GHOST_PORT
      - HEADPHONES_HOST
      - HEADPHONES_PORT
      - HTTPS_PORT
      - HTTP_PORT
      - SICKBEARD_PORT
      - SICKBEARD_HOST
      - SSL_CERTIFICATE
      - SSL_CERTIFICATE_KEY
      - SYNOLOGY_HOST
      - SYNOLOGY_INTERNAL_HOST
      - SYNOLOGY_PORT
      - WEB_INTERNAL_HOST
    volumes:
      - ./automation/certs:/etc/nginx/certs:ro
    ports:
      - "80:${HTTP_PORT}"
      - "443:${HTTPS_PORT}"
