version: "3.7"
x-common-env-vars: &common-env-vars
  PGID: 0
  PUID: 0
  TZ: America/New_York

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      - NAMECHEAP_API_USER
      - NAMECHEAP_API_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
      - ./certs:/certs:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      <<: *common-env-vars
    volumes:
      - /opt/sonarr:/config
      - /media/tv:/tv
      - /media/animu:/animu
    labels:
      - "traefik.enable=true"
      - "traefik.port=8989"
      - "traefik.frontend.rule=Host:tv.muru.io"

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      <<: *common-env-vars
    volumes:
      - /opt/radarr:/config
      - /media/muvis:/movies
    labels:
      - "traefik.enable=true"
      - "traefik.port=7878"
      - "traefik.frontend.rule=Host:muvi.muru.io"

  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    environment:
      <<: *common-env-vars
    ports:
      - "8181:8181"
    volumes:
      - /opt/tautulli:/config
      - /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Sever/Logs/:/logs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.port=8181"
      - "traefik.frontend.rule=Host:plexpy.muru.io"

  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    network_mode: host
    environment:
      <<: *common-env-vars
    volumes:
      - /opt/deluge:/config
      - /media:/downloads
      - /media:/media
