version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      - PUID
      - PGID
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - /opt/sonarr:/config
      - /media/tv:/tv
      - /media/animu:/animu
    ports:
      - "8989:${TV_PORT}"
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - PUID
      - PGID
    volumes:
      - /opt/radarr:/config
      - /media/muvis:/movies
    ports:
      - "7878:${MOVIE_PORT}"
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    restart: always
    network_mode: host
    environment:
      - PUID
      - PGID
      - TZ=America/New_York
    volumes:
      - /media:/downloads
      - /media:/media
      - /opt/deluge:/config
  nginx:
    build:
      context: ./automation/nginx
    container_name: nginx
    image: nginx:latest
    environment:
      - ALLOWED_HOSTS
      - GHOST_PORT
      - HTTPS_PORT
      - HTTP_PORT
      - MOVIE_HOST
      - MOVIE_PORT
      - MUSIC_HOST
      - MUSIC_PORT
      - PLEXPY_HOST
      - PLEXPY_PORT
      - SSL_CERTIFICATE
      - SSL_CERTIFICATE_KEY
      - SYNOLOGY_HOST
      - SYNOLOGY_INTERNAL_HOST
      - SYNOLOGY_PORT
      - TORRENT_HOST
      - TORRENT_PORT
      - TV_HOST
      - TV_PORT
      - WEB_INTERNAL_HOST
    volumes:
      - ./automation/certs:/etc/nginx/certs:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    links:
      - sonarr
      - radarr
    ports:
      - "80:${HTTP_PORT}"
      - "443:${HTTPS_PORT}"
